version: '3'
services:
  node-app-stage1:
    container_name: node-app-stage1
    image: hvxuser/node-app-stage:latest
    restart: always

  node-app-stage2:
    container_name: node-app-stage2
    image: hvxuser/node-app-stage:latest
    restart: always

  node-app-stage3:
    container_name: node-app-stage3
    image: hvxuser/node-app-stage:latest
    restart: always

  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./log/nginx:/var/log/nginx
    depends_on:
      - node-app-stage1
      - node-app-stage2
      - node-app-stage3
