apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-hello-world-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: node-hello-world
  template:
    metadata:
      labels:
        app: node-hello-world 
    spec:
      containers:
        - name: node-app
          image: hvxuser/node-app-stage:latest
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: node-hello-world-service
spec:
  selector:
    app: node-hello-world
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: NodePort
