apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-hello-world-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: node-hello-world
  template:
    metadata:
      labels:
        app: node-hello-world
    spec:
      containers:
        - name: node-hello-world
          image: hvxuser/jenkins:latest
          ports:
            - containerPort: 3000
