version: '3'
services:
  python-app-test1:
    container_name: python-app-test1
    image: hvxuser/python-app-test:latest
    restart: always

  python-app-test2:
    container_name: python-app-test2
    image: hvxuser/python-app-test:latest
    restart: always

  python-app-test3:
    container_name: python-app-test3
    image: hvxuser/python-app-test:latest
    restart: always

  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - 80:80
      - 8000:8000
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./log/nginx:/var/log/nginx
    depends_on:
      - python-app-test1
      - python-app-test2
      - python-app-test3
