version: '3.8'

services:
  node-app:
    image: hvxuser/python-app-test:latest
    deploy:
      replicas: 3
      restart_policy:
        condition: any
      placement:
        constraints:
          - node.role == worker
    ports:
      - 8000:5000
