pipeline {
  agent any

  parameters {
    choice(name: 'DEPLOYMENT_TYPE', choices: ['Docker-Compose', 'Kubernetes'], description: 'Choose the deployment type')
    string(name: 'TARGET_BRANCH', defaultValue: 'dev', description: 'Specify the target branch')
  }

  stages {
    stage('Build') {
      parallel {
        stage('sourcecode') {
          steps {
            git branch: "dev", url: 'https://github.com/yashwanthhvx/Python_App.git'
            echo "Executing from branch: ${env.BRANCH_NAME}"
          }
        }
      }
    }

    stage('Prepare') {
      steps {
        sh "sudo cp -R /var/lib/jenkins/workspace/Jenkins_App_dev/python-app/* /var/lib/jenkins/workspace/Python_App_${params.TARGET_BRANCH}/Python-App/."
      }
    }

    stage('Deploy') {
      parallel {
        stage('Build Image') {
          steps {
            dir('Python-App') {
              sh 'sudo docker build -t python-app-dev .'
              /* sh 'sudo docker run -d -p 8000:5000 --name python-app-dev python-app-dev' */
            }
          }
        }

        stage('Docker Push') {
          steps {
            dir('Python-App') {
              sh 'sudo bash docker-credentials.sh'
              sh 'sudo docker tag python-app-dev:latest hvxuser/python-app-dev'
              sh 'sudo docker push hvxuser/python-app-dev'
            }
          }
        }

        stage('Docker-Compose') {
          when {
            expression { params.DEPLOYMENT_TYPE == 'Docker-Compose' }
          }
          steps {
            dir('Python-App') {
              sh 'sudo docker-compose up -d'
            }
          }
        }

        stage('K8-Deploy') {
          when {
            expression { params.DEPLOYMENT_TYPE == 'Kubernetes' }
          }
          steps {
            dir('Python-App') {
              script {
                def deployCmd = 'sudo kubectl apply -f k8-deployment.yml'
                def deployStatus = sh(script: deployCmd, returnStatus: true)

                if (deployStatus == 0) {
                  echo 'Kubernetes deployment succeeded'
                } else {
                  echo 'Kubernetes deployment failed'
                  currentBuild.result = 'FAILURE'
                }
              }
            }
          }
        }
      }
    }
  }
}
