pipeline {
  agent any

  stages {
    stage('Clone repository') {
      steps {
        git branch: 'test', url: 'https://github.com/yashwanthhvx/Jenkins_App.git'
      }
    }
	
	 stage('Show branch name') {
      steps {
        script {
          def branchName = sh(returnStdout: true, script: 'git rev-parse --abbrev-ref HEAD').trim()
          echo "Executing from branch: ${branchName}"
        }
      }
    }


    stage('Copy the code packages to destination path') {
      steps {
        sh 'sudo cp -R /var/lib/jenkins/workspace/Python_App/Python-App/* /var/lib/jenkins/workspace/Jenkins_App_test/python-app/.'
      }
    }
      
    stage('Build Docker image') {
      steps {
        dir('python-app') {
          sh 'sudo docker build -t python-app:latest .'
        }
      }
    }

    stage('Run Docker container') {
      steps {
        dir('python-app') {
          sh 'sudo docker run -p 80:3000 -d python-app:latest'
        }
      }
    }

    stage('Execute the Bash Script to docker login and save image') {
      steps {
        dir('python-app') {
          sh 'sudo bash docker-credentials.sh'
          sh 'sudo docker tag python-app:latest hvxuser/jenkins'
          sh 'sudo docker push hvxuser/jenkins'
        }
      }
    }

    stage('Create Kubernetes Deployment') {
      steps {
        dir('python-app') {
          script {
            def deployCmd = "sudo kubectl apply -f k8-deployment.yml"
            def deployStatus = sh(script: deployCmd, returnStatus: true)

            if (deployStatus == 0) {
              echo "Kubernetes deployment succeeded"
              currentBuild.result = 'SUCCESS'
            } else {
              echo "Kubernetes deployment failed"
              currentBuild.result = 'FAILURE'
            }
          }
        }
      }
    }

    stage('Create Kubernetes Service') {
      steps {
        dir('node-app') {
          script {
            def serviceCmd = "sudo kubectl apply -f k8-service.yml"
            def serviceStatus = sh(script: serviceCmd, returnStatus: true)

            if (serviceStatus == 0) {
              echo "Kubernetes service creation succeeded"
            } else {
              echo "Kubernetes service creation failed"
            }
          }
        }
      }
    }
  }
}
