apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-hello-world-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: python-hello-world
  template:
    metadata:
      labels:
        app: python-hello-world
    spec:
      containers:
        - name: python-hello-world
          image: hvxuser/python-app-prod:latest
          ports:
            - containerPort: 5000
