apiVersion: v1
kind: Service
metadata:
  name: python-hello-world-service
spec:
  selector:
    app: python-hello-world
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 5000
  type: NodePort
